version: 1.0
Resources:
  - TargetService:
      Type: AWS:ECS::Service
      Properties:
        TaskDefination: "arn:aws:ecs:us-west-2:860061945305:task-definition/sum-pms-eureka:1"
        LoadBalancerInfo:
          ContainerName: sum-eurekaserver
          ContainerPort: "7000"
        PlatformVersion: "LATEST"